var FILL_TYPE;
(function (FILL_TYPE) {
    FILL_TYPE[FILL_TYPE["GRAPHIC_FILL"] = 0] = "GRAPHIC_FILL";
    FILL_TYPE[FILL_TYPE["GRAPHIC_STROKE"] = 1] = "GRAPHIC_STROKE";
})(FILL_TYPE || (FILL_TYPE = {}));
export { FILL_TYPE };
