var COLOR_NAME;
(function (COLOR_NAME) {
    COLOR_NAME[COLOR_NAME["RED"] = 0] = "RED";
    COLOR_NAME[COLOR_NAME["BLUE"] = 1] = "BLUE";
    COLOR_NAME[COLOR_NAME["GREEN"] = 2] = "GREEN";
    COLOR_NAME[COLOR_NAME["YELLOW"] = 3] = "YELLOW";
    COLOR_NAME[COLOR_NAME["PINK"] = 4] = "PINK";
    COLOR_NAME[COLOR_NAME["PURPLE"] = 5] = "PURPLE";
    COLOR_NAME[COLOR_NAME["ORANGE"] = 6] = "ORANGE";
    COLOR_NAME[COLOR_NAME["GOLD"] = 7] = "GOLD";
})(COLOR_NAME || (COLOR_NAME = {}));
export { COLOR_NAME };
